spring.datasource.url: jdbc:h2:file:./camunda-h2-database;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
camunda.bpm.admin-user:
  id: demo
  password: demo
server:
  port: 8900
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: com.reunico.cam.importer.HistoryEventDeserializer
    template:
      default-topic: camunda.history
camunda:
  bpm:
    job-execution:
      core-pool-size: 25 # VSK
      max-pool-size: 50 # VSK
      queue-capacity: 10 # VSK
      max-jobs-per-acquisition: 3 # Number of jobs acquired at once (in the database).
      lock-time-in-millis: 300000 # Time the job will be locked for a specific job executor.
      wait-time-in-millis: 5000 # Idle time for acquisition if no executable job was found

